palette = "catppuccin_mocha"

format = """
$time\
$directory\
$git_branch\
$git_state\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
truncation_length = 3
style = "bold lavender"
read_only = "*"

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[<3](bold green) [>](bold maroon)"
error_symbol = "[/:](bold red) [>](bold maroon)"
vimcmd_symbol = "[<](bold green)"

[git_branch]
format = "[$branch]($style) "
style = "mauve"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "teal"
show_milliseconds = true
min_time = 1_000

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[time]
disabled = false
format = '[$time]($style) '
style = 'bold white'
time_format = '%T'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
# red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
# green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
