return {
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  build = ':TSUpdate',
  opts = {
    ensure_installed = {
      'bash',
      'c',
      'cmake',
      'comment',
      'cpp',
      'diff',
      'dockerfile',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'go',
      'gomod',
      'gowork',
      'gosum',
      'html',
      'json',
      'latex',
      'lua',
      'make',
      'markdown',
      'markdown_inline',
      'perl',
      'python',
      'query',
      'regex',
      'rust',
      'toml',
      'vim',
      'vimdoc',
      'yaml',
    },
    -- Autoinstall languages that are not installed
    highlight = { enable = true },
    indent = { enable = true },
    folds = { enable = true },
  },
}
